spring:
  datasource:
    url: jdbc:postgresql://localhost:6543/lottery
    username: lottery
    password: lottery
  jpa:
    hibernate:
      ddl-auto: none
---
spring:
  profiles: local
logging:
  level:
    org.turkisi: DEBUG
---
spring:
  profiles: automated-tests
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql://localhost:6544/lottery
  shell:
    interactive:
      enabled: false