version: "3.7"
services:
  lottery-postgresql:
    image: postgres:alpine
    ports:
      - 6543:5432
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: lottery
      POSTGRES_PASSWORD: lottery
